[package]
name = "groth16-solana"
version = "0.1.0"
edition = "2021"
authors = ["Bhargav Annem, Yuwen Zhang"]
description = "A Groth16 verifier implementation"
license = "MIT OR Apache-2.0"
repository = "https://github.com/succinctlabs/groth16-solana"
readme = "README.md"
keywords = ["cryptography", "zero-knowledge", "groth16", "verifier"]
categories = ["cryptography"]

[dependencies]
ark-bn254 = "0.4.0"
ark-serialize = "0.4.2"
ark-ff = "0.4.2"
borsh = "1.5.1"
solana-bn254 = { git = "https://github.com/anza-xyz/agave" }
groth16-solana = { git = "https://github.com/sp1-patches/groth16-solana", branch = "patch-v0.0.3" }
thiserror = "1.0.63"

# Optional dependencies for SP1 serialization
sp1-sdk = { version = "2.0.0", default-features = false, optional = true }
hex = { version = "0.4.3", optional = true }
num-bigint = { version = "0.4.6", optional = true }
num-traits = { version = "0.2.19", optional = true }

[features]
default = []
sp1-serialize = ["dep:sp1-sdk", "dep:hex", "dep:num-bigint", "dep:num-traits"]
